from pathlib import Path

from .cache import git_cache

if __name__ == "__main__":
    data = {
        "invenio-access": "4.2.1",
        "invenio-accounts": "6.2.2",
        "invenio-administration": "4.3.2",
        "invenio-app": "2.3.0",
        "invenio-app-rdm": "14.0.0b3.dev6",
        "invenio-assets": "4.2.1",
        "invenio-audit-logs": "0.3.2",
        "invenio-banners": "5.2.1",
        "invenio-base": "2.4.0",
        "invenio-cache": "2.1.0",
        "invenio-celery": "2.2.0",
        "invenio-checks": "2.0.0",
        "invenio-collections": "2.1.0",
        "invenio-communities": "21.2.0",
        "invenio-config": "1.1.0",
        "invenio-db": "2.1.2",
        "invenio-drafts-resources": "7.3.1",
        "invenio-files-rest": "3.4.1",
        "invenio-formatter": "3.3.1",
        "invenio-github": "4.0.0",
        "invenio-i18n": "3.4.3",
        "invenio-indexer": "3.1.0",
        "invenio-jobs": "6.1.0",
        "invenio-jsonschemas": "2.1.0",
        "invenio-logging": "4.1.1",
        "invenio-mail": "2.3.0",
        "invenio-notifications": "1.2.3",
        "invenio-oaiserver": "3.7.4",
        "invenio-oauth2server": "3.3.2",
        "invenio-oauthclient": "6.1.1",
        "invenio-pages": "7.2.1",
        "invenio-pidstore": "2.2.2",
        "invenio-previewer": "3.5.1",
        "invenio-queues": "1.0.2",
        "invenio-rdm-records": "22.7.3",
        "invenio-records": "3.1.1",
        "invenio-records-files": "1.2.1",
        "invenio-records-permissions": "1.2.1",
        "invenio-records-resources": "https://github.com/inveniosoftware/invenio-records-resources?branch=fix-read-many#c6b973a14802e2a7f73100ab4e32cb0c36bd4672",
        "invenio-records-rest": "3.2.1",
        "invenio-records-ui": "2.1.2",
        "invenio-requests": "10.5.0",
        "invenio-rest": "2.0.5",
        "invenio-search": "3.1.2",
        "invenio-search-ui": "4.1.5",
        "invenio-sitemap": "0.3.0",
        "invenio-stats": "5.1.1",
        "invenio-swh": "https://github.com/inveniosoftware/invenio-swh?rev=v0.13.4#828a3a415cf8e725c369939832b61281c44aec40",
        "invenio-theme": "4.5.0",
        "invenio-userprofiles": "4.1.1",
        "invenio-users-resources": "9.0.3",
        "invenio-vocabularies": "9.1.2",
        "invenio-webhooks": "1.1.0",
        "invenio-xrootd": "2.0.0a2",
    }
    for cnt, d in enumerate(data):
        git_cache._clone_repo("inveniosoftware", d)
        pth = Path("/tmp/.invenio_testrig_git_cache/inveniosoftware")
        assert len(list(pth.glob("*"))) == cnt + 1
